<table align="center" width=100%>
    <tr>
        <td width="20%">
            <img src="homework.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                    <b> Takehome - Lab <br>(Day 1)
                    </b>
                </font>
            </div>
        </td>
        <td width="25%">
            <img src="GL-2.png">
        </td>
    </tr>
</table>

### Let's begin with some hands-on practice exercises

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Create an array of integers from 20 to 2 with a step of -2
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [1]:
import numpy as np

In [2]:
np.arange(20,2,-2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Find the minimum value along each of the rows
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

#### Create a 2D Numpy array from list of lists

    num_array = np.array([[110, 102, 183],
                     [140, 175, 106],
                     [170, 195, 117],
                     [192, 140, 195]])

In [8]:
num_array = np.array([[110, 102, 183],
                 [140, 175, 106],
                 [170, 195, 117],
                 [192, 140, 195]])
num_array.min(axis = 1)

array([102, 106, 117, 140])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Replace all odd numbers in the array with -2
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below**<br>
    
       num_array = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])

In [10]:
num_array = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])

num_array[num_array % 2 != 0] = -2
num_array

array([ 0, -2, 42, -2, 34, -2, 26, -2, 38, 94, -2, 78, 76])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Replace all odd numbers in the array 'num_array' with -2 without changing the original array
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below**<br>

    num_array = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])

In [18]:
num_array = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])

modified_array = np.where(num_array % 2 != 0, -2, num_array)
print(modified_array)
num_array

[ 0 -2 42 -2 34 -2 26 -2 38 94 -2 78 76]


array([ 0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Stack two arrays vertically
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    quantity1 = np.arange(10).reshape(2,-1)
    quantity2 = np.repeat(1, 10).reshape(2,-1)

In [26]:
quantity1 = np.arange(10).reshape(2,-1)
print(quantity1)
quantity2 = np.repeat(1, 10).reshape(2,-1)
print(quantity2)

np.vstack([quantity1,quantity2])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Get common elements from the two arrays
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    age_a = np.array([11,12,13,22,23,44,43,24,45,36])
    age_b = np.array([17,22,13,22,47,34,39,44,29,28])

In [28]:
age_a = np.array([11,12,13,22,23,44,43,24,45,36])
age_b = np.array([17,22,13,22,47,34,39,44,29,28])

np.intersect1d(age_a,age_b)

array([13, 22, 44])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Remove all the elements from num_array1 that are present in num_array2
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    num_array1 = np.array([1,2,3,4,5])
    num_array2 = np.array([5,6,7,8,9])

In [32]:
num_array1 = np.array([1,2,3,4,5])
num_array2 = np.array([5,6,7,8,9])

np.setdiff1d(num_array1,num_array2)

array([1, 2, 3, 4])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Get the positions where elements of two arrays match
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    num_array1 = np.array([1,2,3,2,3,4,3,4,5,6])
    num_array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [33]:
num_array1 = np.array([1,2,3,2,3,4,3,4,5,6])
num_array2 = np.array([7,2,10,2,7,4,9,4,9,8])

np.where( )

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Reverse each of the rows of the 2D array
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    num_array1 = np.arange(16).reshape(4,4)

In [39]:
num_array1 = np.arange(16).reshape(4,4)
num_array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
num_array1[ : ,::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Swap row 1 and row 2 in the given array
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>
   
       num_array1 = np.arange(9).reshape(3,3)

In [42]:
num_array1 = np.arange(9).reshape(3,3)
num_array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
num_array1[: :-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a program to add a new column ([5,7]) at the last position in the array given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    array1 = [[[3, 4], [8, 2],[5, 9]]]

In [64]:
array1 = [[[3, 4], [8, 2],[5, 9]]]
array1

[[[3, 4], [8, 2], [5, 9]]]

In [65]:
array1.append([5,7])
array1

[[[3, 4], [8, 2], [5, 9]], [5, 7]]

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a code to combine the two arrays horizontally</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**

    A1 = [[-81, 75, 40], [27, 67, 52]]

    A2 = [[15, 54], [39, 56]]

Combine the array A2 with A1

In [72]:
A1 = [[-81, 75, 40], [27, 67, 52]]

A2 = [[15, 54], [39, 56]]

np.hstack((A1,A2))

array([[-81,  75,  40,  15,  54],
       [ 27,  67,  52,  39,  56]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Write a program to divide the array into two sub-arrays containing equal number of columns
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [77]:
B = np.array([[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1, 3]])

num_columns = B.shape[1]
split_point = num_columns // 2

sub_array1 = B[:, :split_point]
sub_array2 = B[:, split_point:]

print(sub_array1)
print(sub_array2)

[[ 8  7]
 [ 2 -3]
 [ 8  5]]
[[ 0  9]
 [ 5 10]
 [-1  3]]
